//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSM_Analysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mapsuser")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mapsuser")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server= localhost; Database= BingMaps")]
        public string url {
            get {
                return ((string)(this["url"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int noOfRuns {
            get {
                return ((int)(this["noOfRuns"]));
            }
            set {
                this["noOfRuns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int fromToMinDist {
            get {
                return ((int)(this["fromToMinDist"]));
            }
            set {
                this["fromToMinDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int tolerance {
            get {
                return ((int)(this["tolerance"]));
            }
            set {
                this["tolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * from COORDINATES where CITY = \'<AREA>\';")]
        public string areaSelectQuery {
            get {
                return ((string)(this["areaSelectQuery"]));
            }
            set {
                this["areaSelectQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server= localhost; Database= BingMaps; User ID = mapsuser; Password=mapsuser")]
        public string jdbcUrl {
            get {
                return ((string)(this["jdbcUrl"]));
            }
            set {
                this["jdbcUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECLARE @source geography = \'POINT(<POINT1_COR>)\' DECLARE @target geography = \'PO" +
            "INT(<POINT2_COR>)\' SELECT @source.STDistance(@target) as VALUE;")]
        public string disQuery {
            get {
                return ((string)(this["disQuery"]));
            }
            set {
                this["disQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECLARE @g geography; SET @g = geography::STGeomFromText(\'LINESTRING(<CORDINATE_S" +
            "TRING>)\', 4326); DECLARE @source geography = \'POINT(<OSM_POINT>)\';  SELECT @sour" +
            "ce.STDistance(@g) as VALUE;")]
        public string MinDistanceQuery {
            get {
                return ((string)(this["MinDistanceQuery"]));
            }
            set {
                this["MinDistanceQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * from AREA_DEF where CITY = \'<CITY>\' and STATE = \'<STATE>\' and COUNTRY = " +
            "\'<COUNTRY>\' order by MAX_DEF_RANGE;")]
        public string AreaDefQuery {
            get {
                return ((string)(this["AreaDefQuery"]));
            }
            set {
                this["AreaDefQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE from AREA_DEF where CITY = \'<CITY>\';")]
        public string ClearPrevAreaDefEntries {
            get {
                return ((string)(this["ClearPrevAreaDefEntries"]));
            }
            set {
                this["ClearPrevAreaDefEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO AREA_DEF\r\n  ([CITY]\r\n  ,[STATE]\r\n  ,[COUNTRY]\r\n  ,[MAX_DEF_RANGE]\r\n  " +
            ",[AVG_DEFLECTION]\r\n  ,[DATASET_PTS_COUNT]) VALUES \r\n  (\'<CITY>\'\r\n  ,\'<STATE>\'\r\n " +
            " ,\'<COUNTRY>\'\r\n  ,<MAX_DEF_RANGE>\r\n  ,<AVG_DEFLECTION>\r\n  ,<DATASET_PTS_COUNT>);" +
            "")]
        public string AreaDefInsertQuery {
            get {
                return ((string)(this["AreaDefInsertQuery"]));
            }
            set {
                this["AreaDefInsertQuery"] = value;
            }
        }
    }
}
